[package]
name = "pwgen"
version = "1.0.3"
authors = ["Kirk True <kirk@mustardgrain.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
structopt = "0.3.19"
